### PR TITLE
Update udp.py

### PR DESCRIPTION
**Pull request by Bluscream**
now appending the origin client ip to the clientinitiv packet so the server can know the client ip through the proxy (TeaSpeak support for this is coming soon)

### CODE REVIEW

**Comment by derkalle4** [comment]
Hi, please give me some documentation on ts3 server side or a link to an announcement from the Teamspeak Team.

**Comment by Bluscream** [comment]
It won't be supported by official TeamSpeak software but some third party (https://teaspeak.de) and maybe you can use it on official servers through external tools that just grab that packet.

**Comment by derkalle4** [comment]
So you wan't to make a commit to the software without giving further instruction what this code snippet does because there is no documentation on how the server side is using it despite the fact that the original Teamspeak server won't support it? I can't accept this commit without documentation to check wether it's really working this way or not.

**Comment by Bluscream** [comment]
> So you wan't to make a commit

Never said this needs to be merged. pulls are a great way to show people what to patch in order to fix something or add functionality :)

Well even if you don't merge it people can atleast look up how they can make it possible for them. Why would any server document it's internal functions? I can try to explain it for you anyway:

1. ts3proxy will append the original ip to the `clientinitiv` packet
2. teaspeak will get that packet, look for a cip parameter and will store it's contents if it exists
3. when a client on the teaspeak server uses any function that will use or return the ip (`banclient`,`getclientconnectioninfo`,etc) the server will use the IP passed with cip. the actual packet.source ip will only be used to send the packets back to the ts3proxy

> check wether it's really working this way or not.

I will notify you when the first version containing this feature is released.

**Comment by derkalle4** [comment]
Sorry I don't get the point. Didn't you tell me that Teamspeak 3 won't support this? How should the TeamSpeak Server then even look for that? I don't understand. So it won't be useful at any time.

If you send garbage to the Teamspeak 3 Server it will simply discarded or in some circumstances the client connection will get closed. So I don't see that this commit is in any kind useful except you have some kind of documentation that you did not handed out.

**Comment by Bluscream** [comment]
I was talking about **TeaSpeak** not **Teamspeak**

Teamspeak would obviously not implement such a useful feature cause they never listen to anything the community wants.

> If you send garbage to the Teamspeak 3 Server it will simply discarded or in some circumstances the client connection will get closed

I tested that and the official server just ignores that parameter so no problem there :)

**Comment by derkalle4** [comment]
This proxy is not a solution for TeaSpeak, it's for Teamspeak.

**Pull request closed without merging**
